#!/usr/bin/python3
student_scores = input("Input a list of student scores ").split()
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])
print(student_scores)

max = 0
for n in student_scores:
    if n > max:
        max = n

print(f"The highest score in the class is: {max}")
